[package]
name = "mathslib"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mathslib/mathslib"
description = "A math library for Rust"
license = "Apache-2.0"

[dependencies]

[features]
solve = []
optimize = []
stats = []

[lib]
name = "mathslib"
path = "src/lib.rs"